package dymo.auth;

import javax.servlet.*;
import javax.servlet.http.*;
import java.io.IOException;
import dymo.reader.*;

/** 
 * Servlet of authentication reader
 * @version 1.00
 * @author dymo
 * Copyright 2012 The Android Open Source Project
 */
public class AuthenticateServlet extends HttpServlet {

	public void init(ServletConfig config) throws ServletException {
		super.init(config);
	}
   
	public void service(HttpServletRequest req, HttpServletResponse res)
		        throws IOException, ServletException {
   		HttpSession session = req.getSession();
		
   		// Get email and password reader
   		String email = req.getParameter("email");
		String pwd = req.getParameter("password");
		
		// Create an object of class Reader
		Reader rd = new Reader(email, pwd);
		ReaderControl readerControl= new ReaderControl();   

		/* 
		 * We check whether there is such an active reader in the library
		 * If the reader is found, remove session attributes that
		 * generated by servlet then redirected request
		 * a protected document.
		 *
		 * If the reader will not find the request is redirected to an error page */ 
		if (readerControl.authorisationReader(rd) == 1) {
			String protectedPage = (String) session.getAttribute("protected-page");
			
			session.removeAttribute("login-page");
			session.removeAttribute("error-page");
			session.removeAttribute("protected-page");
			session.removeAttribute("login-error");
			session.setAttribute("user", email);
			
			if (protectedPage == null) {
				res.sendRedirect(res.encodeURL("search.html"));
			} else {
				res.sendRedirect(res.encodeURL(protectedPage));
			}
		} else {
			String errorPage = (String) session.getAttribute("error-page");
			if (errorPage == null) {
				res.sendRedirect(res.encodeURL("errorLogining.html"));
			} else {
				res.sendRedirect(res.encodeURL(errorPage));
			}
		}
	}
}
